Changed CreateAmpliconDefinition so that the following error:
Error: Found amplicon: $matching_pcr[0]->setup_name w/ matching primer sequences to your entry, 
but a different amplicon_name param was passed in: $amplicon_name

no longer happens if the amplicon_name was passed in manually.

git-svn-id: svn+ssh://svn/srv/svn/gscpan/perl_modules/trunk@9279 127c0c0e-971a-0410-ad48-868c1a942d8d